version: '3.8'

services:

  drive-db:
    image: postgres
    restart: always
    ports:
      - "5433:5432"  # Mudança da porta do contêiner para 5433
    expose:
      - "5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - driver-ntw

  my-pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "15432:80"
    expose:
      - "80"
    environment:
      PGADMIN_DEFAULT_EMAIL: gabriel-ao@hotmail.com # email de acesso ao pgadmin, pode ser alterado como desejar
      PGADMIN_DEFAULT_PASSWORD: postgres
    networks:
      - driver-ntw
    depends_on:
      - "drive-db"

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
    networks:
      - driver-ntw
    depends_on:
      - "drive-db"

networks:
  driver-ntw:
    driver: bridge
